### ISSUE TITLE
Updating from v4.0.3 to v4.1.0 breaks WKB functions

### ISSUE THREAD

**Issue by mngr777** [zachasme/h3-pg#117]
After the update, `h3_cell_to_boundary_wkb`, `h3_cells_to_multi_polygon_wkb` point to deprecated `h3` functions because of typos in update script: https://github.com/zachasme/h3-pg/blob/dafe3f5b83addce1784db9d5344ab04152d9e5de/h3_postgis/sql/updates/h3_postgis--4.0.3--4.1.0.sql#L22

**Comment by zachasme** [comment]
Oops! I'll get right on it. I needed to release the new postgis_raster functionality anyway.

**Comment by mngr777** [comment]
There seems to be some issue with merging in update script, the functions are re-created with "h3": https://github.com/zachasme/h3-pg/blob/989415f8f6213f05c4fc733907e98801d84dd1b5/h3_postgis/sql/updates/h3_postgis--4.1.0--4.1.1.sql#L41

**Comment by zachasme** [comment]
Thanks for the heads-up, I'll look into it.

I just got a small PR merged into `pg_validate_extupgrade` which should catch these errors in the future!

**Comment by zachasme** [comment]
Should be fixed in `4.1.2` :-)
