### ISSUE TITLE
Getting duplicate primary key errors when using H3INDEX as a PK

### ISSUE THREAD

**Issue by asitemade4u** [zachasme/h3-pg#133]
Hi Zach,

So, following the [excellent article](https://blog.rustprooflabs.com/2023/05/postgis-h3-v4-refresh) of @rustprooflabs I am trying to populate a Postgis table.
Here is the table definition:

```sql
CREATE TABLE h_3.h3x
(
    ref H3INDEX NOT NULL PRIMARY KEY,
    res INT2 NOT NULL,
    geom GEOMETRY (MULTIPOLYGON, 4326) NOT NULL,
    
    CONSTRAINT ck_resolution CHECK (res >= 0 AND res <= 15)
);
CREATE INDEX h3x_hex ON h_3.h3x USING GIST (geom);
```
Following his advice, I am using for primary key (`ref`) the `H3INDEX`.

However, when populating the table from another table with geometry, I get an error about primary key uniqueness:
```bash
[23505] ERROR: duplicate key value violates unique constraint "tst_pkey".
```
And yet, I have exported the values I intend to import to a CSV file and found **no duplicate** in the H3 reference column `ref`...

So, I have two questions:

1. How come I get a unicity error when no reference is alike?
2. Do you discourage using `H3INDEX` as a primary key?

**Comment by zachasme** [comment]
Hi @asitemade4u, thanks for the bug report! It is my intention to allow `H3Index` as primary key, so this should not be happening.

I'll try looking into it myself, but would it be possible for you to provide the csv file with the values that trigger the violation?

**Comment by zachasme** [comment]
Hello again @asitemade4u! I'm having trouble reproducing the problem. It would be a big help if you could send me a sample CSV that produces the error.

**Comment by jmealo** [comment]
@asitemade4u Sorry to revive this after so many years, but, are you able to provide additional info to reproduce this issue?

**Comment by zachasme** [comment]
I'm closing for now, and I'll reopen if anyone manages to reproduce the issue.
