### ISSUE TITLE
Doesn't install h3

### ISSUE THREAD

**Issue by alecburnett** [zachasme/h3-pg#137]
CMake Error at /usr/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find PostgreSQL (missing: PostgreSQL_LIBRARY) (found version
  "13.11")
Call Stack (most recent call first):
  /usr/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindPostgreSQL.cmake:119 (find_package_handle_standard_args)
  CMakeLists.txt:49 (find_package)

**Comment by zachasme** [comment]
Hi @alecburnett! Have you installed the PostgreSQL server headers (postgresql-server-dev-* on ubuntu I believe)?

**Comment by zachasme** [comment]
I'm assuming you've solved your problem. Let me know if this is not the case. Closing for now.
