### ISSUE TITLE
Ubuntu Binary Builds

### ISSUE THREAD

**Issue by graeme44** [zachasme/h3-pg#145]
It seems that only Ubuntu 22.04 and up have binary packages (I've created a [PR](https://github.com/zachasme/h3-pg/pull/144) to update the README). Would it be possible to add Ubuntu 20.04 binary build as well, please? (Unfortunately I'm stuck on an older OS)

**Comment by zachasme** [comment]
I actually don't know who is in charge of the binary packages on apt.postgresql.org. I was made aware of them through #143, which also includes a link to the mailing list where I believe the packagers can be found.

And thanks for the PR!
