### ISSUE TITLE
Error loading the extension

### ISSUE THREAD

**Issue by bertday** [zachasme/h3-pg#151]
Hello! Thank you for this awesome project which has been so helpful to me :)

I'm trying to install h3-pg in a fresh Postgres database and am encountering this error:

```sh
~ ❯ pgxn load h3
INFO: best version: h3 4.1.3
The extension 'h3' doesn't contain a control file:
it will be installed as a loose set of objects.
Do you want to continue? [y/N] y
ERROR: cannot find sql file for extension 'h3': 'h3--4.1.3.sql'
~ ❯    
```

Can anyone help me to understand what's going wrong? I'm on macOS Sonoma, Postgres 15. Thanks!

**Comment by bertday** [comment]
It looks like [this](https://github.com/pgxn/pgxnclient/blob/master/pgxnclient/commands/install.py#L376) is where that error is coming from in `pgxnclient`.

**Comment by bertday** [comment]
May have uncovered a clue in the `pgxnclient` code referenced above: could it be that my `SHAREDIR` is set wrong? 🤔 

```sh
~ ❯ pg_config --sharedir                                                     
/Applications/Postgres.app/Contents/Versions/16/share/postgresql
```

That isn't the Postgres instance I'm trying to load h3-pg into — I'll do some more reading on `SHAREDIR`!

**Comment by bertday** [comment]
Well, this is embarrassing. Somehow h3-pg got uninstalled 😂 Just needed to `pgxn install h3`.

**Comment by zachasme** [comment]
Glad you solved it :sweat_smile: perhaps someone else will find this useful in the future.
