### ISSUE TITLE
Error while installing extension with trigger function that sets privileges

### ISSUE THREAD

**Issue by kdannies** [zachasme/h3-pg#153]
I installed the package via apt, successfully installed the extension on one database. 

On all other databases, when trying to create the extension, the following error occurs:

ERROR: type "h3index" already exists

despite the type h3index not existing in the respective databases.

Any idea whats going wrong?

**Comment by kdannies** [comment]
Was an error in my own setup, I leave it here in case anyone has the same problem:

I have a trigger function that sets priveliges (including owner) on creation of everything when its created, including types. You create the type "h3index" in three steps, and after the creation of the shell, the trigger comes in and changes the owner to something which is not the databaseowner - i have to ask the creator of the trigger the why later i guess. The step after fails then with error seen as above.

After disabling the changing the owner of the type i could install it without error. I will mark it as closed.

**Comment by zachasme** [comment]
Glad you fixed it!

As far as I know, the only way to create a custom PostgreSQL type like h3, is creating a shell type, then the input/output functions and finally redefining the actual type using the input/output functions.
