### ISSUE TITLE
Feature Request: h3_coverage or similar / Documentation update warning of centroid behavior

### ISSUE THREAD

**Issue by jmealo** [zachasme/h3-pg#158]
**See interactive demo here showing the stark difference between `h3_coverage` and `h3_polygon_to_cells`:**
https://h3-snow.streamlit.app/#h3-in-snowflake

Many users of `h3-pg` have use cases outside of Uber's and the upstream `h3` library. It's unclear if they will ever add this functionality, however, it doesn't mean that we couldn't on our end :)

**Problem:**
Most folks using `h3_polygon_to_cells` are expecting behavior closer to `h3_coverage`. One is accurate/slow, the other is inaccurate/fast. I believe both should be available and the differences should be highlighted.

**Follow-up tasks:**
It might make sense to try to see if the upstream `h3` library would be willing to implement this or accept a PR? I'm assuming that they're not interested as SnowFlake implemented it themselves and it doesn't appear necessary for Uber's use case.

An upstream issue opened asking specifically about PostGIS:
https://github.com/uber/h3/issues/842

**Resolution 10:**
<img width="751" alt="Screenshot 2024-10-10 at 12 48 24 PM" src="https://github.com/user-attachments/assets/c4d74ce2-6d44-413f-8f3f-93f5780b3bda">

**Resolution 7:**
<img width="789" alt="Screenshot 2024-10-10 at 12 48 10 PM" src="https://github.com/user-attachments/assets/57944b43-8c5e-4900-a262-a538daa24d76">

**Comment by zachasme** [comment]
Hi @jmealo!

Uber actually merged "support for full containment and overlapping modes in polygonToCellsExperimental" (PR: https://github.com/uber/h3/pull/796), back in November, but I'm still waiting for a release so I can include it in my bindings. I believe that will help with this specific use-case.

Until then, you would have to build `h3-pg` manually with the following changes:
- Change https://github.com/zachasme/h3-pg/blob/main/cmake/h3/CMakeLists.txt to point to H3 master branch
- Change https://github.com/zachasme/h3-pg/blob/main/h3/src/binding/regions.c#L145 to use the new containment mode
- Accept that this might break the upgrade path for `h3-pg`

**Comment by dfellis** [comment]
The reason why it hasn't been released yet is because libfuzzer can detect invalid memory accesses possible with the API on malformed inputs that we haven't figured out, yet (rather, we figured out some of them, but not all of them, yet).

So I would warn against using it on untrusted data, but it should be perfectly fine for actual usage.

**Comment by jmealo** [comment]
@dfellis: Thanks for the context. I'm seeing very odd behavior with invalid inputs in general:
https://github.com/uber/h3/issues/926

**Comment by dfellis** [comment]
Right. I haven't commented on that one because it's kinda the Geospatial equivalent of a [Klein bottle](https://en.wikipedia.org/wiki/Klein_bottle) so I feel like the behavior of the code (making the rest of the world part of the polygon) is more "correct" than interpreting it as two conjoined polygons, but I also know that interpretation is less useful, so I am torn.

**Comment by jmealo** [comment]
@zachasme: I gave this a shot, but, I'm not great with CMake or C in general... I'm not sure if `h3` isn't exporting this in `h3api.h` or if I'm doing something wrong?

https://github.com/zachasme/h3-pg/pull/159

**Comment by jmealo** [comment]
@zachasme: If you try to feed this invalid geometry, you can/will get an error and then there's the issue of possible invalid memory access mentioned by @dfellis. `ST_IsValid` is so cheap to run, I think it might make sense just to call it internally and raise an exception ourselves rather than risk it.

**Comment by zachasme** [comment]
@dfellis Thanks for the heads-up :-) Would you consider releasing a new version of H3 core with the new polygon to cells algorithm as `polygonToCellsExperimental`, as it currently is on the master branch? What are you doing for own bindings (h3-js, h3-py)? 

@jmealo Thanks for moving on this. I don't know how to do ST_IsValid from the C-side, currently I'm doing a lot of SQL layer PostGIS calls in the `h3-postgis` extension. Let's continue that discussion in #157.

**Comment by zachasme** [comment]
That's great to hear @dfellis! I'll keep the bindings in sync with whatever you release :+1: Thanks for the good work on H3!
