### ISSUE TITLE
Add GiST and SP-GiST support

### ISSUE THREAD

**Issue by zachasme** [zachasme/h3-pg#5]
We should support GiST and SP-GiST indexes for operations like contains and contained by.

Ongoing work in separate PRs:
* GiST in #42
* SP-GiST in #43

**Comment by AbelVM** [comment]
Hi, any news on this? The [PR](https://github.com/bytesandbrains/h3-pg/pull/7) looks stalled as it's 1 year old, but there's no info on the blockers or the status.

**How can we help?** :hammer:

**Comment by zachasme** [comment]
Hi Abel, I've commented on the PR with a status.

**Comment by AbelVM** [comment]
Cool, we will take a look at it. I have some ideas I'd like to test :smiley: 

But first, I have a question related to [these functions](https://github.com/bytesandbrains/h3-pg/pull/7/files#diff-142e7aae7fea21db52c9cb96eeb06111R29) (`gist_cmp` and `common_ancestor`, mainly) in the PR: You have defined a lot of bitwise logic in `h3index.h`, but then in the index related functions, you use high-level methods from the core API instead. Is there any reason for that? Looks like a lot of redundant  (implicit) operations to me :thinking:

**Comment by zachasme** [comment]
That sounds great :smiley: 

You are correct that the bitwise logic is mostly unused. I have directly copied `h3index.h` from the h3 repository since I needed the `H3_GET_INDEX_DIGIT` macro. I actually made this related issue https://github.com/uber/h3/issues/277 since it is not exposed to library consumers.

The branch is very much a work-in-progress, and it would probably better to only include the necessary macros.

**Comment by AbelVM** [comment]
As you asked for some references about GiST:
* [GiST bible](http://www.sai.msu.su/~megera/postgres/gist/)
* PostGIS implementation (`gserialized_gist*.*` a bit spread over [here](https://github.com/postgis/postgis/tree/master/libpgcommon) and [here](https://github.com/postgis/postgis/tree/master/postgis))

And, regarding the bitwise version, I just made a [PR](https://github.com/bytesandbrains/h3-pg/pull/40) instead of a codeblock in this comment  :)

**Comment by zachasme** [comment]
I've split the old branch into two, so we can get GiST working and merged before moving on to SP-GiST.

**Comment by multi3spectral** [comment]
Hi, you mentioned above that using the GiST index can lead to slower results - is there more known about the causes of this? Are some kinds of queries more affected than others?

**Comment by zachasme** [comment]
It is not a problem with GiST generally, but a problem with my initial implementation. Specifically I need to come up with good algorithms for `penalty` and `picksplit` (see https://www.postgresql.org/docs/current/gist-extensibility.html). I just haven't yet been able to dedicate the time necessary to solve this.

**Comment by zachasme** [comment]
Discussion continued in:
* GiST in #42
* SP-GiST in #43
