### ISSUE TITLE
C-compiler issues on macOS Monterey 12.3.1

### ISSUE THREAD

**Issue by nasushkov** [zachasme/h3-pg#82]
Hi, 
I'm trying to install the extension as described on macOS Monterey 12.3.1 (running on the Apple M1 Pro, if it makes the difference). However, it has some issues with the C-compiler and fails with the following error:

> -- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - broken
> CMake Error at /opt/homebrew/Cellar/cmake/3.24.2/share/cmake/Modules/CMakeTestCCompiler.cmake:69 (message):
>   The C compiler
> 
>     "/Library/Developer/CommandLineTools/usr/bin/cc"
> 
>   is not able to compile a simple test program.
> 
>   It fails with the following output:
> 
>     Change Dir: /private/var/folders/1k/h710l67j5ylc7lkpwvy2cdxh0000gn/T/tmp2pkicv0k/h3-4.0.0/libh3-v4.0.0-rc5/build/CMakeFiles/CMakeTmp
> 
>     Run Build Command(s):/opt/homebrew/bin/gmake -f Makefile cmTC_be14c/fast && gmake[1]: Entering directory '/private/var/folders/1k/h710l67j5ylc7lkpwvy2cdxh0000gn/T/tmp2pkicv0k/h3-4.0.0/libh3-v4.0.0-rc5/build/CMakeFiles/CMakeTmp'
>     /opt/homebrew/bin/gmake  -f CMakeFiles/cmTC_be14c.dir/build.make CMakeFiles/cmTC_be14c.dir/build
>     gmake[2]: Entering directory '/private/var/folders/1k/h710l67j5ylc7lkpwvy2cdxh0000gn/T/tmp2pkicv0k/h3-4.0.0/libh3-v4.0.0-rc5/build/CMakeFiles/CMakeTmp'
>     Building C object CMakeFiles/cmTC_be14c.dir/testCCompiler.c.o
>     /Library/Developer/CommandLineTools/usr/bin/cc   -fPIC -fvisibility=hidden -flto -fwrapv -mpc64  -arch arm64 -arch x86_64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk -std=gnu99 -MD -MT CMakeFiles/cmTC_be14c.dir/testCCompiler.c.o -MF CMakeFiles/cmTC_be14c.dir/testCCompiler.c.o.d -o CMakeFiles/cmTC_be14c.dir/testCCompiler.c.o -c /private/var/folders/1k/h710l67j5ylc7lkpwvy2cdxh0000gn/T/tmp2pkicv0k/h3-4.0.0/libh3-v4.0.0-rc5/build/CMakeFiles/CMakeTmp/testCCompiler.c
>     clang: error: unknown argument: '-mpc64'
>     gmake[2]: *** [CMakeFiles/cmTC_be14c.dir/build.make:79: CMakeFiles/cmTC_be14c.dir/testCCompiler.c.o] Error 1
>     gmake[2]: Leaving directory '/private/var/folders/1k/h710l67j5ylc7lkpwvy2cdxh0000gn/T/tmp2pkicv0k/h3-4.0.0/libh3-v4.0.0-rc5/build/CMakeFiles/CMakeTmp'
>     gmake[1]: *** [Makefile:127: cmTC_be14c/fast] Error 2
>     gmake[1]: Leaving directory '/private/var/folders/1k/h710l67j5ylc7lkpwvy2cdxh0000gn/T/tmp2pkicv0k/h3-4.0.0/libh3-v4.0.0-rc5/build/CMakeFiles/CMakeTmp'
> 
> 
> 
> 
> 
>   CMake will not be able to correctly generate this project.
> Call Stack (most recent call first):
>   CMakeLists.txt:75 (project)

**Comment by zachasme** [comment]
I believe this was introduced in #75 and fixed in #78. I just have to get around to releasing a new version with the changes. I'll try to get it out today.
