### ISSUE TITLE
postgres.h not found error

### ISSUE THREAD

**Issue by apiszcz** [zachasme/h3-pg#92]
postgres-14 with the following ubuntu 22.04 packages

 postgis \
                        pgxnclient \
                        postgis-doc \
                        postgresql \
                        postgresql-14 \
                        postgresql-14-cron \
                        postgresql-14-extra-window-functions \
                        postgresql-14-pgrouting-doc \
                        postgresql-14-pointcloud \
                        postgresql-14-postgis-3 \
                        postgresql-14-postgis-3-scripts \
                        postgresql-14-similarity \
                        postgresql-14-toastinfo \
                        postgresql-14-unit \
                        postgresql-server-dev-14 \
                        postgresql-contrib-14 \
                        pspg \
                        osm2pgsql \
                        libproj-dev \
                        libjson-c-dev \
                        libprotobuf-c-dev

```
#17 9.954 gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g -g -O2 -flto=auto -ffat-lto-objects -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security -fno-omit-frame-pointer -flto -mpc64 -fPIC -Ilibh3-v4.0.1/build/src/h3lib/include -Ih3/src -I. -I./ -I/usr/include/postgresql/15/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2   -c -o h3/src/deprecated.o h3/src/deprecated.c
#17 9.958 h3/src/deprecated.c:17:10: fatal error: postgres.h: No such file or directory
#17 9.958    17 | #include <postgres.h>
#17 9.958       |          ^~~~~~~~~~~~
#17 9.958 compilation terminated.
#17 9.959 gmake: *** [<builtin>: h3/src/deprecated.o] Error 1
#17 9.960 ERROR: command returned 2: gmake PG_CONFIG=/usr/bin/pg_config all
```

**Comment by mmc1718** [comment]
I am also having this problem - what was your solution?

**Comment by zachasme** [comment]
Do you have PostgreSQL server headers installed? If you are on Ubuntu, can you confirm that you have the package `postgresql-server-dev`?

**Comment by mmc1718** [comment]
Just checked, I had the wrong version installed that didn't match my version of postgres. Working now :) Thanks!
