### ISSUE TITLE
H3 <> PostGIS Raster

### ISSUE THREAD

**Issue by Komzpa** [zachasme/h3-pg#95]
We at Kontur are implementing h3_pg <> PostGIS raster interop. We've been using it internally for a while and are looking to get out to this extension. This is invaluable thing to be building things like Kontur population dataset (https://www.kontur.io/portfolio/population-dataset/). However there is a concern that it will introduce a new dependency onto postgis_raster extension for the raster datatype. Is it ok to add such a dependency directly to `h3_postgis`, or should there be some other way?

cc @zachasme @mngr777

**Comment by zachasme** [comment]
I'm very interested to see what kind of interop you've implemented!

Is the `postgis_raster` extension generally available on PostGIS installations? Then I think it would be ok to add as an additional dependency for `h3_postgis`. Otherwise we can add a third extension `h3_postgis_raster`.

**Comment by Komzpa** [comment]
`postgis_raster` is available on all installations except those where someone took their time to build a custom with it disabled. I also think it should be okay to add it as dependency. 

The interop for now is fairly simple, a set of functions to take the raster imported by raster2pgsql and summarize it into h3 cells (as sum if you're dealing with population, as average if that's some kind of elevation, ...).

Hope we'll return with PRs soon :)

**Comment by zachasme** [comment]
I'll be looking forward to it :)
